# Generated by Django 5.2.4 on 2025-07-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_registered_student_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_background',
            name='year_of_completion_of_primary_school',
            field=models.CharField(blank=True, null=True),
        ),
    ]
