# Generated by Django 5.2.4 on 2025-07-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_academic_background_year_of_completion_of_primary_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_emergency_contact_persons',
            name='postal_box_a',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_emergency_contact_persons',
            name='postal_box_b',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_personal_data',
            name='postal_box',
            field=models.CharField(blank=True, null=True),
        ),
    ]
