# Generated by Django 5.2.4 on 2025-07-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_emergency_contact_persons_postal_box_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_background',
            name='index_number_of_primary_school',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic_background',
            name='index_number_of_secondary_school',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_family_information',
            name='number_of_brothers_and_sisters',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_personal_data',
            name='number_of_children_if_married',
            field=models.CharField(blank=True, null=True),
        ),
    ]
