# Generated by Django 5.2.4 on 2025-07-25 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_department_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturers',
            field=models.ManyToManyField(blank=True, related_name='lecturers', to=settings.AUTH_USER_MODEL),
        ),
    ]
