# Generated by Django 5.2.4 on 2025-07-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/submissions'),
        ),
    ]
