# Generated by Django 5.2.4 on 2025-07-21 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_background',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_data', to='lecturers.lecturer'),
        ),
        migrations.AlterField(
            model_name='lecturer_emergency_contact_persons',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emmergency_contacts', to='lecturers.lecturer'),
        ),
        migrations.AlterField(
            model_name='lecturer_family_information',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='lecturers.lecturer'),
        ),
        migrations.AlterField(
            model_name='lecturer_residence',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residence', to='lecturers.lecturer'),
        ),
    ]
