# Generated by Django 5.2.4 on 2025-07-21 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0002_alter_academic_background_lecturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer_emergency_contact_persons',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='lecturers.lecturer'),
        ),
    ]
