# Generated by Django 5.2.4 on 2025-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0003_alter_lecturer_emergency_contact_persons_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_background',
            name='year_of_completion_of_secondary_school',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
